Small layout improvements.
graphile/bootstrap-react-apollo pull request #6
Opened 2019-03-08 23:01 UTC by nicolad

Small POC.

2019-03-08 23:05 UTC, nicolad commented
@benjie what's your thoughts on this ?
Maybe you can add some specific issues since authorization and authentication is not yet hooked on server side ?

2019-03-09 07:54 UTC, benjie requested changes
LGTM 👍 Just fix the hyphens and we’re good to merge.

2019-03-09 07:54 UTC, benjie commented on client/src/components/Layout/Article.js
> +  minheight: calc(100vh - 5rem);
min-height (missing hyphen)

2019-03-09 07:54 UTC, benjie commented on client/src/components/Layout/Footer.js
> +  backgroundcolor: #eee;
Missing hyphen

2019-03-09 20:48 UTC, nicolad commented
Updated.

2019-03-09 21:07 UTC, benjie approved these changes

2019-03-09 21:09 UTC, merged